### ISSUE TITLE
Make Docker Compose setup stable

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-deployment#13]
As a developer
I want the Docker Compose to work always
So that I don't have to try it more then once

Background:
After starting docker compose and going to localhost the login is always shown.
But after the logging OpenSCD not always starts, there are loading errors of all JS and so files.
We need to investigate why this is happening.

**Comment by Sander3003** [comment]
It is fine if the offline mode for CoMPAS is disabled.

**Comment by dlabordus** [comment]
This issue set the solution of the worker processes 1.
https://github.com/zmartzone/lua-resty-openidc/issues/206
