### ISSUE TITLE
Create Github action for AWS deployment

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-deployment#95]
**User Story**

As a maintainer

I want to deploy new CoMPAS versions to AWS in an automatic way

So that demo.compas.energy stays current with the development of CoMPAS.

**Acceptance criteria**

Github action (with at least 2 steps)

**To do**
Create a new AWS task definition withe the latest version
Deploy the task definition

** Background **

https://github.com/aws-actions/amazon-ecs-deploy-task-definition#task-definition-file

**Comment by Sander3003** [comment]
Still todo: Remove trigger secondairy triggers

**Comment by Sander3003** [comment]
It is work in progress.

**Comment by pascalwilbrink** [comment]
Fixed by #106
